// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisSGgKf5lIK_N0LmopIc0TA1Bm-1HJG4',
    appId: '1:586491477090:web:d13d43fdaeb8935ce2253b',
    messagingSenderId: '586491477090',
    projectId: 'sql-test-app-af681',
    authDomain: 'sql-test-app-af681.firebaseapp.com',
    storageBucket: 'sql-test-app-af681.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw0zO-8ykOHelQXMyRhe2icjtCDLWvd1M',
    appId: '1:586491477090:android:aa9c4e40a1691c36e2253b',
    messagingSenderId: '586491477090',
    projectId: 'sql-test-app-af681',
    storageBucket: 'sql-test-app-af681.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9nDMtr2yNC6Is-CtftQi_eQKvUR4QYwI',
    appId: '1:586491477090:ios:c270dbde39aa09ace2253b',
    messagingSenderId: '586491477090',
    projectId: 'sql-test-app-af681',
    storageBucket: 'sql-test-app-af681.appspot.com',
    iosBundleId: 'com.example.sqlTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9nDMtr2yNC6Is-CtftQi_eQKvUR4QYwI',
    appId: '1:586491477090:ios:c270dbde39aa09ace2253b',
    messagingSenderId: '586491477090',
    projectId: 'sql-test-app-af681',
    storageBucket: 'sql-test-app-af681.appspot.com',
    iosBundleId: 'com.example.sqlTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAisSGgKf5lIK_N0LmopIc0TA1Bm-1HJG4',
    appId: '1:586491477090:web:1cf443dfde04b105e2253b',
    messagingSenderId: '586491477090',
    projectId: 'sql-test-app-af681',
    authDomain: 'sql-test-app-af681.firebaseapp.com',
    storageBucket: 'sql-test-app-af681.appspot.com',
  );
}
